name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: env GOOS=linux GOARCH=arm64 go build -o prepnode_arm64
